apiVersion: apps/v1
kind: Deployment
metadata:
  # name of deployment
  name: alpine-basic
spec:
  replicas: 1
  selector:
    # matching selectors for pods
    matchLabels:
      app: alpine-basic
  minReadySeconds: 10
  strategy:
    # Type of deployment. Can be "Recreate" or "RollingUpdate". Default is RollingUpdate.
    type: RollingUpdate
    rollingUpdate:
      # The maximum number of pods that can be unavailable during the update. 
      # Value can be an absolute number (ex: 5) or a percentage of desired pods (ex: 10%). 
      maxUnavailable: 1
      # The maximum number of pods that can be scheduled above the desired number of pods. Value can be an absolute 
      # number (ex: 5) or a percentage of desired pods (ex: 10%). 
      maxSurge: 1
  # Template describes the pods that will be created.
  template:
    metadata:
      # labels of the pod
      labels:
        app: alpine-basic
    # Pod Spec
    spec:
      containers:
      - name: alpine-basic-pod
        image: wilfredt/alpine-basic
