apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  # labels of this service
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
    # ServicePort array. So we need to supply array here
      # port exposed by service
    - port: 8080
      # port on each node
      nodePort: 30001
      protocol: TCP
  # Route service traffic to pods with label keys and values matching this selector. 
  selector:
    app: hello-world
